### PR TITLE
Fix mailto in html entites used on github profile page

### PR DESCRIPTION
**Pull request by jcubic**
Fix for #64

### CODE REVIEW

**Comment by mtibben** [comment]
Hi @jcubic, thanks for the contribution however I don't understand what this is fixing. Could you

1. provide a detailed description in this Pull Request explaining what this doing, and why, using examples
2. provide test cases to demonstrate that the fix does in fact work

**Comment by jcubic** [comment]
On github user profile page there are links that look like this:
```html
<a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;%6a%63%75%62%69%63@%6a%63%75%62%69%63.%70%6c">jcubic@jcubic.pl</a>
```
and if you display result on html page, `&#109;&#97;&#105;&#108;&#116;&#111;&#58;` is replaced by mailto: but it's not decoded so the link have slash `/mailto:`.

**Comment by jcubic** [comment]
Added 2 tests for mailto one with html entities.

**Comment by mtibben** [comment]
Fixed in 7d78d00976318f0c154afdfe5a016c95850fb28d

**Pull request closed without merging**
